// ============================================================================
// 200-AGENT REGISTRY - Complete Agent Definitions
// ============================================================================

import { AgentCategory, AgentConfig } from './types';

const createAgent = (id: string, name: string, category: AgentCategory, description: string, priority: number): AgentConfig => ({
  id,
  name,
  category,
  description,
  enabled: true,
  priority,
  maxRetries: 3,
  timeout: 30000,
});

export const AGENT_REGISTRY: AgentConfig[] = [
  // ========== SEO AGENTS (40 agents) ==========
  createAgent('seo-001', 'Keyword Research Master', AgentCategory.SEO, 'AI-powered keyword discovery and analysis', 95),
  createAgent('seo-002', 'Competitor Keyword Analyzer', AgentCategory.SEO, 'Analyze competitor keyword strategies', 90),
  createAgent('seo-003', 'Long-tail Keyword Generator', AgentCategory.SEO, 'Generate long-tail keyword variations', 85),
  createAgent('seo-004', 'Search Intent Classifier', AgentCategory.SEO, 'Classify keywords by search intent', 88),
  createAgent('seo-005', 'Keyword Difficulty Scorer', AgentCategory.SEO, 'Score keyword difficulty and opportunity', 87),
  createAgent('seo-006', 'Semantic Keyword Extractor', AgentCategory.SEO, 'Extract semantic variations of keywords', 86),
  createAgent('seo-007', 'Geographic Keyword Localizer', AgentCategory.SEO, 'Localize keywords for geo-targeting', 82),
  createAgent('seo-008', 'Voice Search Optimizer', AgentCategory.SEO, 'Optimize for voice search queries', 83),
  createAgent('seo-009', 'Featured Snippet Targeting', AgentCategory.SEO, 'Target featured snippet positions', 89),
  createAgent('seo-010', 'Meta Title Optimizer', AgentCategory.SEO, 'Generate SEO-optimized meta titles', 92),
  createAgent('seo-011', 'Meta Description Generator', AgentCategory.SEO, 'Create compelling meta descriptions', 91),
  createAgent('seo-012', 'URL Structure Optimizer', AgentCategory.SEO, 'Optimize URL structure for SEO', 84),
  createAgent('seo-013', 'Internal Link Builder', AgentCategory.SEO, 'Strategic internal linking system', 90),
  createAgent('seo-014', 'Schema Markup Generator', AgentCategory.SEO, 'Generate JSON-LD structured data', 93),
  createAgent('seo-015', 'Breadcrumb Generator', AgentCategory.SEO, 'Create SEO-friendly breadcrumbs', 80),
  createAgent('seo-016', 'Heading Tag Optimizer', AgentCategory.SEO, 'Optimize H1-H6 tag hierarchy', 91),
  createAgent('seo-017', 'Image Alt Text Generator', AgentCategory.SEO, 'Generate descriptive alt text for images', 88),
  createAgent('seo-018', 'Image Compression Agent', AgentCategory.SEO, 'Compress and optimize images', 85),
  createAgent('seo-019', 'Canonical URL Manager', AgentCategory.SEO, 'Manage canonical URL tags', 87),
  createAgent('seo-020', 'Hreflang Manager', AgentCategory.SEO, 'Implement hreflang tags for multi-language', 86),
  createAgent('seo-021', 'Mobile Usability Checker', AgentCategory.SEO, 'Verify mobile-first design compliance', 89),
  createAgent('seo-022', 'Core Web Vitals Optimizer', AgentCategory.SEO, 'Optimize LCP, FID, CLS scores', 94),
  createAgent('seo-023', 'Page Speed Analyzer', AgentCategory.SEO, 'Analyze and improve page load speed', 92),
  createAgent('seo-024', 'Sitemap Generator', AgentCategory.SEO, 'Generate XML sitemaps', 88),
  createAgent('seo-025', 'Robots.txt Generator', AgentCategory.SEO, 'Create optimized robots.txt', 82),
  createAgent('seo-026', 'Crawl Error Detector', AgentCategory.SEO, 'Detect and fix crawl errors', 87),
  createAgent('seo-027', 'Redirect Manager', AgentCategory.SEO, 'Manage 301/302 redirects', 85),
  createAgent('seo-028', 'Duplicate Content Detector', AgentCategory.SEO, 'Find and resolve duplicate content', 89),
  createAgent('seo-029', 'Thin Content Analyzer', AgentCategory.SEO, 'Identify and improve thin content', 86),
  createAgent('seo-030', 'SERP Feature Tracker', AgentCategory.SEO, 'Track featured snippets, knowledge panels', 87),
  createAgent('seo-031', 'Keyword Gap Analyzer', AgentCategory.SEO, 'Identify ranking gaps vs competitors', 88),
  createAgent('seo-032', 'SERP Volatility Monitor', AgentCategory.SEO, 'Monitor ranking fluctuations', 84),
  createAgent('seo-033', 'Algorithm Update Tracker', AgentCategory.SEO, 'Track Google algorithm changes', 86),
  createAgent('seo-034', 'Rich Snippet Optimizer', AgentCategory.SEO, 'Optimize for rich snippets', 91),
  createAgent('seo-035', 'AMP Page Optimizer', AgentCategory.SEO, 'Create AMP versions for mobile', 79),
  createAgent('seo-036', 'Noindex/Nofollow Manager', AgentCategory.SEO, 'Manage crawl directives', 81),
  createAgent('seo-037', 'Page Experience Scorer', AgentCategory.SEO, 'Score overall page experience', 90),
  createAgent('seo-038', 'HTTPS/SSL Enforcer', AgentCategory.SEO, 'Enforce HTTPS security', 88),
  createAgent('seo-039', 'XML Sitemap Validator', AgentCategory.SEO, 'Validate XML sitemaps', 80),
  createAgent('seo-040', 'SEO Audit Reporter', AgentCategory.SEO, 'Generate comprehensive SEO audits', 92),

  // ========== CONTENT AGENTS (35 agents) ==========
  createAgent('content-001', 'AI Content Writer', AgentCategory.CONTENT, 'Generate SEO-optimized content', 94),
  createAgent('content-002', 'Content Enhancer', AgentCategory.CONTENT, 'Improve existing content quality', 91),
  createAgent('content-003', 'Keyword Density Optimizer', AgentCategory.CONTENT, 'Optimize keyword density naturally', 88),
  createAgent('content-004', 'Readability Improver', AgentCategory.CONTENT, 'Improve content readability scores', 89),
  createAgent('content-005', 'Plagiarism Detector', AgentCategory.CONTENT, 'Detect and prevent plagiarism', 87),
  createAgent('content-006', 'Content Freshness Agent', AgentCategory.CONTENT, 'Update and refresh old content', 85),
  createAgent('content-007', 'Semantic Content Optimizer', AgentCategory.CONTENT, 'Add semantic richness to content', 90),
  createAgent('content-008', 'Topic Cluster Builder', AgentCategory.CONTENT, 'Create topic clusters and pillar content', 89),
  createAgent('content-009', 'Outline Generator', AgentCategory.CONTENT, 'Generate content outlines', 86),
  createAgent('content-010', 'FAQ Generator', AgentCategory.CONTENT, 'Create FAQ sections', 84),
  createAgent('content-011', 'Call-to-Action Optimizer', AgentCategory.CONTENT, 'Optimize CTAs for conversions', 87),
  createAgent('content-012', 'Headline Generator', AgentCategory.CONTENT, 'Generate compelling headlines', 92),
  createAgent('content-013', 'Blog Post Generator', AgentCategory.CONTENT, 'Generate complete blog posts', 93),
  createAgent('content-014', 'Product Description Writer', AgentCategory.CONTENT, 'Write product descriptions', 88),
  createAgent('content-015', 'Email Content Generator', AgentCategory.CONTENT, 'Generate email marketing content', 85),
  createAgent('content-016', 'Social Media Content Creator', AgentCategory.CONTENT, 'Create social media posts', 86),
  createAgent('content-017', 'Video Script Generator', AgentCategory.CONTENT, 'Generate video scripts', 84),
  createAgent('content-018', 'Infographic Creator', AgentCategory.CONTENT, 'Generate infographic content', 81),
  createAgent('content-019', 'Multilingual Translator', AgentCategory.CONTENT, 'Translate content to multiple languages', 89),
  createAgent('content-020', 'Content Localization Agent', AgentCategory.CONTENT, 'Localize content for different regions', 88),
  createAgent('content-021', 'Case Study Builder', AgentCategory.CONTENT, 'Generate case study content', 87),
  createAgent('content-022', 'Whitepaper Generator', AgentCategory.CONTENT, 'Create technical whitepapers', 86),
  createAgent('content-023', 'Webinar Outline Creator', AgentCategory.CONTENT, 'Create webinar outlines', 83),
  createAgent('content-024', 'Podcast Script Writer', AgentCategory.CONTENT, 'Write podcast scripts', 82),
  createAgent('content-025', 'News Article Generator', AgentCategory.CONTENT, 'Generate news-style articles', 85),
  createAgent('content-026', 'Listicle Generator', AgentCategory.CONTENT, 'Create listicle content', 84),
  createAgent('content-027', 'How-To Guide Writer', AgentCategory.CONTENT, 'Write step-by-step guides', 87),
  createAgent('content-028', 'Comparison Content Creator', AgentCategory.CONTENT, 'Create comparison content', 86),
  createAgent('content-029', 'Review Content Generator', AgentCategory.CONTENT, 'Generate product/service reviews', 85),
  createAgent('content-030', 'Testimonial Generator', AgentCategory.CONTENT, 'Generate compelling testimonials', 83),
  createAgent('content-031', 'Quote Generator', AgentCategory.CONTENT, 'Generate relevant quotes for content', 80),
  createAgent('content-032', 'Content Calendar Planner', AgentCategory.CONTENT, 'Plan content calendar', 82),
  createAgent('content-033', 'Content Performance Analyzer', AgentCategory.CONTENT, 'Analyze content performance', 88),
  createAgent('content-034', 'Repurposing Agent', AgentCategory.CONTENT, 'Repurpose content across formats', 86),
  createAgent('content-035', 'Content Personalization Engine', AgentCategory.CONTENT, 'Personalize content for users', 89),

  // ========== TECHNICAL AGENTS (30 agents) ==========
  createAgent('tech-001', 'Schema.org Validator', AgentCategory.TECHNICAL, 'Validate structured data markup', 90),
  createAgent('tech-002', 'JSON-LD Generator', AgentCategory.TECHNICAL, 'Generate JSON-LD structured data', 92),
  createAgent('tech-003', 'Microdata Implementer', AgentCategory.TECHNICAL, 'Implement microdata markup', 87),
  createAgent('tech-004', 'Open Graph Optimizer', AgentCategory.TECHNICAL, 'Optimize Open Graph tags', 89),
  createAgent('tech-005', 'Twitter Card Manager', AgentCategory.TECHNICAL, 'Manage Twitter card tags', 86),
  createAgent('tech-006', 'Semantic HTML5 Converter', AgentCategory.TECHNICAL, 'Convert to semantic HTML5', 88),
  createAgent('tech-007', 'CSS Performance Optimizer', AgentCategory.TECHNICAL, 'Optimize CSS for performance', 87),
  createAgent('tech-008', 'JavaScript Minifier', AgentCategory.TECHNICAL, 'Minify and optimize JavaScript', 89),
  createAgent('tech-009', 'CDN Configuration Agent', AgentCategory.TECHNICAL, 'Configure CDN for static assets', 85),
  createAgent('tech-010', 'Caching Strategy Optimizer', AgentCategory.TECHNICAL, 'Optimize caching strategies', 88),
  createAgent('tech-011', 'HTTP Headers Optimizer', AgentCategory.TECHNICAL, 'Optimize HTTP headers', 86),
  createAgent('tech-012', 'Security Headers Implementer', AgentCategory.TECHNICAL, 'Add security headers', 87),
  createAgent('tech-013', 'SSL Certificate Manager', AgentCategory.TECHNICAL, 'Manage SSL certificates', 85),
  createAgent('tech-014', 'DNS Optimizer', AgentCategory.TECHNICAL, 'Optimize DNS records', 84),
  createAgent('tech-015', 'Server Response Time Optimizer', AgentCategory.TECHNICAL, 'Optimize server response times', 89),
  createAgent('tech-016', 'Database Query Optimizer', AgentCategory.TECHNICAL, 'Optimize database queries', 88),
  createAgent('tech-017', 'API Performance Monitor', AgentCategory.TECHNICAL, 'Monitor API performance', 86),
  createAgent('tech-018', 'Web Accessibility Checker', AgentCategory.TECHNICAL, 'Verify WCAG compliance', 87),
  createAgent('tech-019', 'Structured Data Debugger', AgentCategory.TECHNICAL, 'Debug structured data issues', 85),
  createAgent('tech-020', 'Mobile Rendering Tester', AgentCategory.TECHNICAL, 'Test mobile rendering', 86),
  createAgent('tech-021', 'Browser Compatibility Checker', AgentCategory.TECHNICAL, 'Test browser compatibility', 84),
  createAgent('tech-022', 'Performance Monitoring Agent', AgentCategory.TECHNICAL, 'Monitor page performance metrics', 89),
  createAgent('tech-023', 'Uptime Monitor', AgentCategory.TECHNICAL, 'Monitor website uptime', 87),
  createAgent('tech-024', 'Error Log Analyzer', AgentCategory.TECHNICAL, 'Analyze server error logs', 85),
  createAgent('tech-025', 'Load Testing Agent', AgentCategory.TECHNICAL, 'Perform load testing', 83),
  createAgent('tech-026', 'Analytics Implementation Checker', AgentCategory.TECHNICAL, 'Verify analytics tracking', 88),
  createAgent('tech-027', 'Conversion Tracking Validator', AgentCategory.TECHNICAL, 'Validate conversion tracking', 87),
  createAgent('tech-028', 'Lighthouse Scorer', AgentCategory.TECHNICAL, 'Run and analyze Lighthouse scores', 90),
  createAgent('tech-029', 'Web Vitals Monitor', AgentCategory.TECHNICAL, 'Monitor Core Web Vitals', 91),
  createAgent('tech-030', 'Third-party Script Auditor', AgentCategory.TECHNICAL, 'Audit third-party scripts impact', 86),

  // ========== AUTHORITY AGENTS (25 agents) ==========
  createAgent('auth-001', 'Backlink Builder', AgentCategory.AUTHORITY, 'Find and build high-quality backlinks', 95),
  createAgent('auth-002', 'Competitor Backlink Analyzer', AgentCategory.AUTHORITY, 'Analyze competitor backlinks', 92),
  createAgent('auth-003', 'Broken Link Finder', AgentCategory.AUTHORITY, 'Find broken link opportunities', 89),
  createAgent('auth-004', 'Link Opportunity Scout', AgentCategory.AUTHORITY, 'Scout for linking opportunities', 90),
  createAgent('auth-005', 'Guest Post Outreach', AgentCategory.AUTHORITY, 'Manage guest post outreach', 88),
  createAgent('auth-006', 'Resource Page Finder', AgentCategory.AUTHORITY, 'Find resource pages to target', 87),
  createAgent('auth-007', 'Citation Builder', AgentCategory.AUTHORITY, 'Build local citations', 86),
  createAgent('auth-008', 'Press Release Distributor', AgentCategory.AUTHORITY, 'Distribute press releases', 85),
  createAgent('auth-009', 'Link Anchor Text Optimizer', AgentCategory.AUTHORITY, 'Optimize anchor text strategy', 89),
  createAgent('auth-010', 'HARO Responder', AgentCategory.AUTHORITY, 'Respond to HARO queries', 84),
  createAgent('auth-011', 'Unlinked Brand Mention Finder', AgentCategory.AUTHORITY, 'Find unlinked brand mentions', 88),
  createAgent('auth-012', 'Relationship Manager', AgentCategory.AUTHORITY, 'Manage influencer relationships', 85),
  createAgent('auth-013', 'Domain Authority Tracker', AgentCategory.AUTHORITY, 'Track domain authority metrics', 87),
  createAgent('auth-014', 'Referring Domain Monitor', AgentCategory.AUTHORITY, 'Monitor referring domains', 86),
  createAgent('auth-015', 'Link Quality Scorer', AgentCategory.AUTHORITY, 'Score link quality', 88),
  createAgent('auth-016', 'Toxic Link Remover', AgentCategory.AUTHORITY, 'Identify and remove toxic links', 87),
  createAgent('auth-017', 'Link Reclamation Agent', AgentCategory.AUTHORITY, 'Reclaim lost or redirected links', 86),
  createAgent('auth-018', 'Industry Directory Submitter', AgentCategory.AUTHORITY, 'Submit to industry directories', 81),
  createAgent('auth-019', 'Local Listing Manager', AgentCategory.AUTHORITY, 'Manage local business listings', 84),
  createAgent('auth-020', 'Review Aggregator', AgentCategory.AUTHORITY, 'Aggregate reviews across platforms', 83),
  createAgent('auth-021', 'Brand Authority Builder', AgentCategory.AUTHORITY, 'Build overall brand authority', 89),
  createAgent('auth-022', 'Expert Positioning Agent', AgentCategory.AUTHORITY, 'Position team as experts', 85),
  createAgent('auth-023', 'Media Coverage Tracker', AgentCategory.AUTHORITY, 'Track media mentions', 84),
  createAgent('auth-024', 'Award Submission Agent', AgentCategory.AUTHORITY, 'Submit for industry awards', 80),
  createAgent('auth-025', 'Speaking Opportunity Finder', AgentCategory.AUTHORITY, 'Find speaking opportunities', 82),

  // ========== SOCIAL AGENTS (20 agents) ==========
  createAgent('social-001', 'Social Media Poster', AgentCategory.SOCIAL, 'Post to social media', 88),
  createAgent('social-002', 'Hashtag Optimizer', AgentCategory.SOCIAL, 'Optimize hashtags', 85),
  createAgent('social-003', 'Social Engagement Monitor', AgentCategory.SOCIAL, 'Monitor social engagement', 86),
  createAgent('social-004', 'Community Manager', AgentCategory.SOCIAL, 'Manage social communities', 84),
  createAgent('social-005', 'Influencer Finder', AgentCategory.SOCIAL, 'Find relevant influencers', 87),
  createAgent('social-006', 'Social Listening Monitor', AgentCategory.SOCIAL, 'Monitor brand mentions', 88),
  createAgent('social-007', 'Sentiment Analyzer', AgentCategory.SOCIAL, 'Analyze social sentiment', 86),
  createAgent('social-008', 'Viral Content Creator', AgentCategory.SOCIAL, 'Create viral-worthy content', 89),
  createAgent('social-009', 'Social Ad Manager', AgentCategory.SOCIAL, 'Manage social media ads', 87),
  createAgent('social-010', 'User-Generated Content Curator', AgentCategory.SOCIAL, 'Curate UGC', 83),
  createAgent('social-011', 'Twitter Thread Creator', AgentCategory.SOCIAL, 'Create Twitter threads', 84),
  createAgent('social-012', 'LinkedIn Article Publisher', AgentCategory.SOCIAL, 'Publish LinkedIn articles', 85),
  createAgent('social-013', 'Instagram Story Optimizer', AgentCategory.SOCIAL, 'Optimize Instagram stories', 82),
  createAgent('social-014', 'TikTok Video Generator', AgentCategory.SOCIAL, 'Generate TikTok videos', 80),
  createAgent('social-015', 'YouTube Optimization Agent', AgentCategory.SOCIAL, 'Optimize YouTube videos', 88),
  createAgent('social-016', 'Social Analytics Tracker', AgentCategory.SOCIAL, 'Track social analytics', 85),
  createAgent('social-017', 'Crisis Response Agent', AgentCategory.SOCIAL, 'Manage social crises', 89),
  createAgent('social-018', 'Comment Responder', AgentCategory.SOCIAL, 'Respond to social comments', 82),
  createAgent('social-019', 'Social Calendar Planner', AgentCategory.SOCIAL, 'Plan social calendar', 83),
  createAgent('social-020', 'Cross-Platform Publisher', AgentCategory.SOCIAL, 'Publish across platforms', 86),

  // ========== VELOCITY AGENTS (15 agents) ==========
  createAgent('velocity-001', 'Ranking Boost Engine', AgentCategory.VELOCITY, 'Accelerate ranking gains', 94),
  createAgent('velocity-002', 'Algorithm Update Response', AgentCategory.VELOCITY, 'Respond to algo changes', 92),
  createAgent('velocity-003', 'Fresh Content Accelerator', AgentCategory.VELOCITY, 'Accelerate fresh content rankings', 91),
  createAgent('velocity-004', 'Link Velocity Monitor', AgentCategory.VELOCITY, 'Monitor link acquisition velocity', 89),
  createAgent('velocity-005', 'Traffic Surge Detector', AgentCategory.VELOCITY, 'Detect traffic surges', 88),
  createAgent('velocity-006', 'Ranking Change Tracker', AgentCategory.VELOCITY, 'Track ranking changes', 87),
  createAgent('velocity-007', 'SERP Position Simulator', AgentCategory.VELOCITY, 'Simulate SERP positions', 90),
  createAgent('velocity-008', 'Predictive Ranker', AgentCategory.VELOCITY, 'Predict future rankings', 93),
  createAgent('velocity-009', 'Momentum Builder', AgentCategory.VELOCITY, 'Build ranking momentum', 91),
  createAgent('velocity-010', 'Quick Win Identifier', AgentCategory.VELOCITY, 'Identify quick ranking wins', 88),
  createAgent('velocity-011', 'Rapid Testing Agent', AgentCategory.VELOCITY, 'Run rapid A/B tests', 86),
  createAgent('velocity-012', 'Keyword Bid Manager', AgentCategory.VELOCITY, 'Manage keyword bidding', 84),
  createAgent('velocity-013', 'CTR Booster', AgentCategory.VELOCITY, 'Boost click-through rates', 89),
  createAgent('velocity-014', 'Impression Maximizer', AgentCategory.VELOCITY, 'Maximize impressions', 87),
  createAgent('velocity-015', 'Real-time Optimizer', AgentCategory.VELOCITY, 'Optimize in real-time', 92),

  // ========== CONVERSION AGENTS (15 agents) ==========
  createAgent('conversion-001', 'Conversion Rate Optimizer', AgentCategory.CONVERSION, 'Optimize conversion rates', 91),
  createAgent('conversion-002', 'Landing Page Generator', AgentCategory.CONVERSION, 'Generate high-converting landing pages', 92),
  createAgent('conversion-003', 'Form Optimizer', AgentCategory.CONVERSION, 'Optimize forms for conversions', 89),
  createAgent('conversion-004', 'Checkout Optimizer', AgentCategory.CONVERSION, 'Optimize checkout process', 90),
  createAgent('conversion-005', 'Copy Optimizer', AgentCategory.CONVERSION, 'Optimize sales copy', 88),
  createAgent('conversion-006', 'Value Proposition Creator', AgentCategory.CONVERSION, 'Create compelling value props', 87),
  createAgent('conversion-007', 'A/B Test Manager', AgentCategory.CONVERSION, 'Manage A/B testing', 89),
  createAgent('conversion-008', 'Heatmap Analyzer', AgentCategory.CONVERSION, 'Analyze user heatmaps', 85),
  createAgent('conversion-009', 'User Journey Mapper', AgentCategory.CONVERSION, 'Map user journeys', 86),
  createAgent('conversion-010', 'Exit-intent Trigger Optimizer', AgentCategory.CONVERSION, 'Optimize exit-intent offers', 84),
  createAgent('conversion-011', 'Personalization Engine', AgentCategory.CONVERSION, 'Personalize user experience', 88),
  createAgent('conversion-012', 'Trust Signal Implementer', AgentCategory.CONVERSION, 'Add trust signals', 86),
  createAgent('conversion-013', 'Social Proof Optimizer', AgentCategory.CONVERSION, 'Optimize social proof', 87),
  createAgent('conversion-014', 'Email Sequence Optimizer', AgentCategory.CONVERSION, 'Optimize email sequences', 85),
  createAgent('conversion-015', 'Remarketing Campaign Manager', AgentCategory.CONVERSION, 'Manage remarketing campaigns', 86),
];

export function getAgentsByCategory(category: AgentCategory): AgentConfig[] {
  return AGENT_REGISTRY.filter(agent => agent.category === category);
}

export function getAgentById(id: string): AgentConfig | undefined {
  return AGENT_REGISTRY.find(agent => agent.id === id);
}

export function getAllAgents(): AgentConfig[] {
  return AGENT_REGISTRY;
}

export function getTotalAgentCount(): number {
  return AGENT_REGISTRY.length;
}
